/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminPasswords.java
 *
 * Created on May 20, 2010, 9:20:54 PM
 */

package integartedfarmsystem;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Magondu
 */
public class AdminPasswords extends javax.swing.JFrame {
char oldpassword[] = new char [20] ;
char newpassword[] = new char [20];
char repeatpassword[] = new char [20];
    /** Creates new form AdminPasswords */
    public AdminPasswords() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OldPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        RepeatPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Backbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Old password:");

        jLabel2.setText("New password:");

        jLabel3.setText("Repeat new password:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("CHANGE ADMIN PASSWORD");

        OkButton.setText("OK");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Backbutton.setText("Back");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("MARINA LIVESTOCK FARM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OkButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RepeatPassword)
                            .addComponent(OldPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cancel)
                                .addGap(18, 18, 18)
                                .addComponent(Backbutton))
                            .addComponent(NewPassword))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RepeatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OkButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Backbutton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed

       AdminTask win = new AdminTask();
        win.setVisible(true);
        this.dispose();
}//GEN-LAST:event_BackbuttonActionPerformed

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
      try{

      oldpassword = OldPassword.getPassword();
      newpassword = NewPassword.getPassword();
      repeatpassword = RepeatPassword.getPassword();
      String Oldpasswordstring = String.copyValueOf(oldpassword);
      String newpasswordstring = String.copyValueOf(newpassword);
      String repeatpasswordstring = String.copyValueOf(repeatpassword);
   
         Class.forName("com.mysql.jdbc.Driver");
   Connection conect = DriverManager.getConnection("jdbc:mysql://localhost:3306/integratedfarmsystemnnew", "root", "");
             Statement stmt = conect.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                     ResultSet.CONCUR_READ_ONLY);
ResultSet srs = stmt.executeQuery(
    "SELECT password FROM loginadmin");
while (srs.next()) {
      String Dbasepassword = srs.getString("password");
      
      if (Dbasepassword.compareTo(Oldpasswordstring)==0)
      {
          if (newpasswordstring.compareTo(repeatpasswordstring)==0)
      {
         PreparedStatement pstmt0 = conect.prepareStatement("DELETE FROM `integratedfarmsystemnnew`.`loginadmin` WHERE password =\"" +Dbasepassword+"\"");
         pstmt0.executeUpdate();
          PreparedStatement pstmt = conect.prepareStatement("INSERT INTO loginadmin(password) value(?)") ;
          pstmt.setString(1, newpasswordstring);
          pstmt.executeUpdate();
          JOptionPane.showMessageDialog(null, "The password has been changed");      }
          else if(newpasswordstring.compareTo(repeatpasswordstring)!=0)
          { JOptionPane.showMessageDialog(null, "your new passwords do not match");}

      }
      else if(Dbasepassword.compareTo(Oldpasswordstring)!=0)
      {JOptionPane.showMessageDialog(null, "The password you have entered does not match with the one in the database");}
}}
catch(SQLException e)
			{
				System.out.println("2 Error : "+e);
			}
			catch(Exception ex)
			{
				System.out.println("Error 1:"+ex);
			}

    }//GEN-LAST:event_OkButtonActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        int yesNo =JOptionPane.YES_NO_OPTION;
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "CONFIRMATION", yesNo);

if (option == JOptionPane.YES_OPTION)
{
    this.dispose();
}
else
{
JOptionPane.showMessageDialog(null, "YOU HAVE ABORTED THE CANCEL OPERATION");
}
    }//GEN-LAST:event_CancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPasswords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton Cancel;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JButton OkButton;
    private javax.swing.JPasswordField OldPassword;
    private javax.swing.JPasswordField RepeatPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
