/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminTasks.java
 *
 * Created on May 15, 2010, 10:29:04 PM
 */

package integartedfarmsystem;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Magondu
 */
public class AdminTasks extends javax.swing.JFrame {

    /** Creates new form AdminTasks */
    public AdminTasks() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewUserAccounts = new javax.swing.JButton();
        ChangePassword = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ChangeUserPaswords = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        DeleteUserAccount = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Create new user accounts:");

        jLabel2.setText("Change admin password:");

        NewUserAccounts.setText("here");
        NewUserAccounts.setContentAreaFilled(false);
        NewUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserAccountsActionPerformed(evt);
            }
        });

        ChangePassword.setText("here");
        ChangePassword.setContentAreaFilled(false);
        ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(153, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setForeground(new java.awt.Color(51, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN TASKS");
        jLabel4.setOpaque(true);

        jLabel6.setText("Change user passwords:");

        ChangeUserPaswords.setText("here");
        ChangeUserPaswords.setContentAreaFilled(false);
        ChangeUserPaswords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeUserPaswordsActionPerformed(evt);
            }
        });

        jLabel7.setText("Delete a user account:");

        DeleteUserAccount.setText("here");
        DeleteUserAccount.setContentAreaFilled(false);
        DeleteUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserAccountActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                        .add(NewUserAccounts))
                    .add(layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 47, Short.MAX_VALUE)
                        .add(DeleteUserAccount))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                        .add(ChangePassword))
                    .add(layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 37, Short.MAX_VALUE)
                        .add(ChangeUserPaswords)))
                .add(94, 94, 94))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .add(Cancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(47, 47, 47)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(NewUserAccounts))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(DeleteUserAccount))
                        .add(18, 18, 18)
                        .add(jLabel2))
                    .add(ChangePassword))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(ChangeUserPaswords))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Cancel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserAccountsActionPerformed
    try{
  
        String username = JOptionPane.showInputDialog(null, "Enter the user name");
        String password = JOptionPane.showInputDialog(null, "Please enter the password");
        String password2 = JOptionPane.showInputDialog(null, "Please enter the password again");

        if (password.compareTo(password2)== 0)
        {
         Class.forName("com.mysql.jdbc.Driver");
   Connection conect = DriverManager.getConnection("jdbc:mysql://localhost:3306/integratedfarmsystemnnew", "root", "");
            PreparedStatement pstmt = conect.prepareStatement(
    "INSERT into loginuser(username,password)  values(?,?)");
            pstmt.setString(1, username);
            pstmt.setString(2, password);
            pstmt.executeUpdate();
        }
        else
        {
        JOptionPane.showMessageDialog(null, "incorrect password match");
        }
    }
catch(SQLException e)
			{
				System.out.println("2 Error : "+e);
			}
			catch(Exception ex)
			{
				System.out.println("Error 1:"+ex);
			}

    }//GEN-LAST:event_NewUserAccountsActionPerformed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed

 AdminPasswords win = new AdminPasswords();
 win.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void ChangeUserPaswordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeUserPaswordsActionPerformed

        try
        {
           
        String username = JOptionPane.showInputDialog(null,"please enter the account username");
        String password = JOptionPane.showInputDialog(null,"please enter the new password");
         int option = JOptionPane.showConfirmDialog(null, "are you sure you want to change the user account "+username
                +" by inserting the passsword "+password);
       if (option == JOptionPane.YES_OPTION)
          {
         Class.forName("com.mysql.jdbc.Driver");
       Connection conect = DriverManager.getConnection("jdbc:mysql://localhost:3306/integratedfarmsystemnnew", "root", "");
       PreparedStatement pstmt = conect.prepareStatement("UPDATE loginuser SET password = ? WHERE username like ?");
            pstmt.setString(1, password);
            pstmt.setString(2, username);
            pstmt.executeUpdate();
          }
          else
          {
          JOptionPane.showMessageDialog(null, "your changes have NOT been saved");
          }
         }// TODO add your handling code here:
                    catch(SQLException e)
			{
				System.out.println("2 Error : "+e);
			}
			catch(Exception ex)
			{
				System.out.println("Error 1:"+ex);
			}

    }//GEN-LAST:event_ChangeUserPaswordsActionPerformed

    private void DeleteUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserAccountActionPerformed

     String UsernameToDelete = JOptionPane.showInputDialog(null,"Enter the username of the account you want deleted");
     int option = JOptionPane.showConfirmDialog(null, "Are you sure yo want to delete the useraccount "+ UsernameToDelete+" ?");
       if (option == JOptionPane.YES_OPTION)
          {
           try{
         Class.forName("com.mysql.jdbc.Driver");
       Connection conect = DriverManager.getConnection("jdbc:mysql://localhost:3306/integratedfarmsystemnnew", "root", "");
       PreparedStatement pstmt = conect.prepareStatement("DELETE FROM loginuser WHERE username = ?");
            pstmt.setString(1, UsernameToDelete);
            pstmt.executeUpdate();
          }
            catch(SQLException e)
			{
				System.out.println("2 Error : "+e);
			}
			catch(Exception ex)
			{
				System.out.println("Error 1:"+ex);
			}
       }
    }//GEN-LAST:event_DeleteUserAccountActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
  int yesNo =JOptionPane.YES_NO_OPTION;
        int option = JOptionPane.showConfirmDialog(this, "ARE YOU SURE YOU WANT TO EXIT?", "CONFIRMATION", yesNo);

if (option == JOptionPane.YES_OPTION)
{
    this.dispose();
}
else
{
JOptionPane.showMessageDialog(null, "YOU HAVE ABORTED THE CANCEL OPERATION");
}
                                                
    }//GEN-LAST:event_CancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton ChangePassword;
    private javax.swing.JButton ChangeUserPaswords;
    private javax.swing.JButton DeleteUserAccount;
    private javax.swing.JButton NewUserAccounts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
